codestates-beb/BEB-06-SECOND-02

- client/package-lock.json
- client/package.json
- client/src/App.js
- client/src/Pages/AccountPage.js
- client/src/components/AccountComponents/AccountContents.js
- client/src/components/AccountComponents/AccountInfo.js
- client/src/components/Header.js
- client/src/components/HeaderButton.js
- client/src/components/LoginModal.js
- client/src/utils/modal.css
- server/.env.example
- server/node_modules/.package-lock.json
- server/node_modules/http-errors/HISTORY.md
- server/node_modules/http-errors/README.md
- server/node_modules/http-errors/index.js
- server/node_modules/http-errors/package.json
ex) feature/login -> dev
login 시에 account 정보 가져오기 로직 구현해 놓았습니다. Login Modal id password 입력란에 글씨가 하얀색으로나와서 검은색으로 다시 바꿨씁니다.
현재 DB에 저장된 User는 heeinpark / password 이 유저 밖에 없으므로,
id 에 heeinpark
password 에 password 입력하시고 로그인 하시면 됩니다!
> [client] / #4 / edit : login 해서 account 정보 Get 구현, modal textcolor 변경

- client/src/Pages/DetailPage.js
- client/src/Pages/WritePage.js
- client/src/components/Review.js
- client/src/components/WriteForm.js
UI 구성만 해놨습니다.
게시물 작성은 DB 업데이트 함수만 작성하면 됩니다.
> WritePage, DetailPage

- client/src/App.js
- client/src/Pages/AccountPage.js
- client/src/components/AccountComponents/AccountSend.js
- client/src/components/Header.js
- client/src/components/LoginModal.js
- client/src/utils/AccountPage.css
hyungu main -> main 
accountPage에 이미지 업로드 기능 넣어놨고, 추후에 component로 바꿀 예정니다. 그래서 어디든 컴포넌트로 css만 만져서 재사용 가능하게끔요
> [client] / #5 / accountPage에 img upload 틀 잡기

- client/src/components/SignupModal.js
- package-lock.json
- server/controller/users.js
> Signup Complete(without hashing)

- client/src/Pages/WritePage.js
- client/src/components/WriteForm.js
- server/app.js
- server/controller/articles.js
- server/controller/users.js
- server/model/article.js
ex) Login-JWT-Implementation-> dev
writePage의 jwt 관련 로직을 추가합니다.
서버 사이드에서 Postman으로 테스트한 결과 jwt를 헤더로 넘기면 작동됩니다.
> [server][client] refactor: writepage & token implementation

- client/src/App.js
- client/src/Pages/AccountPage.js
- client/src/Pages/MainPage.js
- client/src/components/Header.js
- client/src/components/LoginModal.js
- client/src/index.css
- client/src/utils/MainPage.css
- server/controller/users.js
- server/model/user.js
- server/router/users.js
DB에 프로필 사진 저장할 수 있도록 했습니다. 
user/login 할때 저장된 img 도 같이 불러옵니다.
하지만, /refresh할때도 img를 불러오게 됩니다. -> 이부분 수정이 필요할수도..
> [client] / #8 / 프로필사진 DB저장 및, 로그인시 가져오기.

- client/src/Pages/WritePage.js
- client/src/components/Review.js
- client/src/components/WriteForm.js
- server/app.js
- server/controller/articles.js
- server/model/article.js
> [client] / #9 / Write upload Img 구현

- client/src/App.js
- client/src/Pages/AccountPage.js
- client/src/Pages/MainPage.js
- client/src/components/Comments.js
- client/src/components/ListContainer.js
- client/src/components/LoginModal.js
mainPage refactoring
ListComponents 파일 만들었습니다.
MainPage에서 Axios다루려면, 코드가 너무 길어질거같아 아예 컴포넌트 하나 만들었어요~
> [client] / #10 / mainpage refactor

- server/app.js
- server/controller/web3.js
- server/router/web3.js
- server/utility/abi.json
- server/utility/sendtoken.js
- server/utility/web3provider.js
token reward utility 및 user token send API
> token reward, user token send

- client/src/Pages/AccountPage.js
- client/src/Pages/MainPage.js
- client/src/components/AccountComponents/AccountContents.js
- client/src/components/Articles.js
- client/src/components/Comments.js
- client/src/components/Header.js
- client/src/components/HeaderButton.js
- client/src/components/ListContainer.js
- client/src/index.css
- client/src/utils/AccountPage.css
- client/src/utils/Articles.css
- client/src/utils/Comments.css
- client/src/utils/Font.css
- client/src/utils/MainPage.css
> [client] / # 12 / styling comments components

- client/src/Pages/AccountPage.js
- server/controller/articles.js
- server/controller/regions.js
- server/controller/users.js
- server/controller/web3.js
- server/model/article.js
- server/model/region.js
- server/router/users.js
ex) dev -> main
데이터베이스에 있는 Region 도큐먼트를 불러오거나
글 쓰기 과정 중 Region을 설정할 수 있는 기능 추가
> [Server]/ #8 / Region Model 및 API

- client/src/App.js
- client/src/Pages/MainPage.js
- client/src/components/Article.js
- client/src/components/HeaderButton.js
- client/src/components/ListContainer.js
- client/src/index.css
- client/src/utils/Article.css
- client/src/utils/MainPage.css
> [client] / #14 / style: Article과 메인페이지 색 정했습니다.

- client/src/App.js
- client/src/Pages/WritePage.js
- client/src/components/AccountComponents/AccountSend.js
- client/src/components/Header.js
- client/src/components/LoginModal.js
- server/controller/articles.js
- server/controller/users.js
- server/controller/web3.js
- server/utility/sendtoken.js
> token send

- server/controller/articles.js
- server/controller/users.js
- server/model/user.js
회원가입할 때, save() 전 타당성 검사하면서 일어난 버그로 인해 생긴 오류였습니다.
> [server] / 회원가입 오류 고침

- client/src/App.js
- client/src/Pages/AccountPage.js
- client/src/Pages/MainPage.js
- client/src/Pages/WritePage.js
- client/src/components/AccountComponents/AccountContents.js
- client/src/components/ListContainer.js
- client/src/components/ListContainerByRegion.js
- client/src/components/LoginModal.js
- client/src/components/Review.js
- client/src/components/WriteForm.js
- server/app.js
- server/controller/articles.js
- server/controller/regions.js
- server/controller/users.js
- server/router/regions.js
writepage 에 selector 구현했습니다. 아직 미완성입니다. 급히 Merge해서 진행해야해서 pr 올립니다.
> [client] / #14 / writepage selector

- server/app.js
- server/controller/articles.js
- server/controller/regions.js
- server/controller/users.js
- server/model/article.js
- server/model/region.js
- server/router/articles.js
- server/router/regions.js
> [server] / Quick Fix: Filter 수정

- server/controller/articles.js
- server/controller/users.js
- server/model/article.js
- server/model/user.js
- server/utility/createaccount.js
ex) dev -> main
article/like로 patch api 명령어를 보내면, 글을 like할 수 있는 기능을 추가했습니다.
json body 형태로 { articleId }를 전달하면 좋아요를 누르지 않았을 경우에는 좋아요 유저 배열에 사용자를 추가하고
눌렀을 경우 목록에서 삭제합니다.
> [Server]/ Like Patch API 추가

- client/src/App.js
- client/src/Pages/AccountPage.js
- client/src/Pages/DetailPage.js
- client/src/Pages/MainPage.js
- client/src/Pages/WritePage.js
- client/src/components/Article.js
- client/src/components/Comments.js
- client/src/components/Footer.js
- client/src/components/Header.js
- client/src/components/ListContainerByRegion.js
- client/src/components/LoginModal.js
- client/src/components/Review.js
- client/src/utils/AccountPage.css
- client/src/utils/Article.css
- client/src/utils/MainPage.css
- server/controller/users.js
imgSrc 대신 userProfileImg 로 변경하였고,
mainpage에서 articles불러올때 profileImg도 같이 불러오게 되었습니다.
commnets는 작성중이시니 건들이진 않았습니다. avatar부분 -> 댓글 달면 프로필사진 보이는것만 src 를 none으로 바꿧습니다.
> [client] / #17 / context 수정, imgSrc , setImgSrc 컨텍스트는 현재 사용하지 않습니다.

- client/src/App.js
- client/src/Pages/AccountPage.js
- client/src/Pages/MainPage.js
- client/src/components/Header.js
- client/src/components/ListContainer.js
- client/src/components/WriteForm.js
- server/controller/regions.js
- server/controller/users.js
```
// profile 사진 업로드.
const uploadProfile = async (req, res) => {
const { profileImage } = req.body;
try {
const token = req.cookies.token;
const data = jwt.verify(token, process.env.SECRET);
const userId = data.userId;
const user = await User.updateOne({ userId: userId }, { profileImage: profileImage });
res.status(200).json({ user });
} catch (error) {
const msg = {};
msg[`${error.name}`] = `${error.message}`;
console.error(`${error.name} : ${error.message}`);
res.status(400).json(msg);
}
};
```
프로필 사진 올릴 때 로그인 인증 필요하게 수정했습니다.
> [Server] quick fix: profileImage

- client/src/App.js
- client/src/Pages/AccountPage.js
- client/src/Pages/MintPage.js
- client/src/components/AccountComponents/AccountContents.js
- client/src/components/AccountComponents/AccountInfo.js
- client/src/components/AccountComponents/AccountNft.js
- client/src/components/AccountComponents/AccountSend.js
- client/src/components/Article.js
- client/src/components/Header.js
- client/src/components/HeaderButton.js
- client/src/components/Skeleton.js
- client/src/utils/AccountPage.css
- 스타일링.
- 
AccountPage 스타일링입니다.
Skeleton.js는 accountPage 에 있는 NFT 들입니다.
> [client] / #18 / AccountPage 스타일링.

- client/src/Pages/MainPage.js
- client/src/Pages/WritePage.js
- client/src/components/ListContainer.js
- client/src/components/WriteForm.js
MainPage와 WritePage 등등 Takoyaki-Region DB에서 지역 리스트를 불러오는 페이지와 컴포넌트에 DB 연동을 추가했습니다.
이를 통해 게시물에서 유효한 지역을 반영할 수 있습니다.
또한 하드 코딩으로 불일치할 수 있는 데이터를 일관성 있게 유지할 수 있습니다.
> [Server] 지역 데이터 연동되는 부분 추가

- client/src/App.js
- client/src/Pages/AccountPage.js
- client/src/Pages/DetailPage.js
- client/src/Pages/MainPage.js
- client/src/Pages/WritePage.js
- client/src/components/AccountComponents/AccountNft.js
- client/src/components/Article.js
- client/src/components/Footer.js
- client/src/components/Review.js
- client/src/components/WriteForm.js
- client/src/utils/AccountPage.css
- client/src/utils/WritePage.css
> [client] / #18 / AcocuntPage styling

- client/src/components/ListContainer.js
- server/controller/articles.js
- server/controller/regions.js
- server/router/articles.js
articles/:id라는 get api를 추가하여, article id를 파라미터로 보내면 단일 아티클 가져오게 했습니다.
> [server] 단일 글 불러오는 API

- client/src/Pages/MintPage.js
- server/controller/web3.js
> [quick] / #2 / api 키 감추기
